<script lang="ts">
	import PageHeader from '$lib/components/PageHeader.svelte';
	import { formatDateTime, money } from '$lib/data';
	import { ArrowUpRight, Download, Search } from '@lucide/svelte';
	import type { Invoice, Order } from '$lib/types';

	let { data }: { data: { orders: Order[]; invoices: Invoice[] } } = $props();
	let query = $state('');
	const rows = $derived(data.invoices.map((invoice) => ({ invoice, order: data.orders.find((order) => order.id === invoice.orderId) })).filter(({ invoice, order }) => `${invoice.number} ${order?.customer || ''} ${order?.project || ''}`.toLowerCase().includes(query.toLowerCase())));
</script>

<PageHeader eyebrow="Bills and payment tracking" title="Invoices" />
<div class="invoice-summary"><div><span>Outstanding</span><strong>{money(data.orders.reduce((sum,order)=>sum+(order.priceSet===false?0:Math.max(0,order.price-order.discount-order.paid)),0))}</strong></div><div><span>Collected</span><strong>{money(data.orders.reduce((sum,order)=>sum+order.paid,0))}</strong></div><a class="secondary" href="/api/export"><Download size={13}/> Export .xlsx</a></div>
<div class="invoice-tools"><div class="filter"><Search size={14}/><input bind:value={query} placeholder="Search invoices"/></div><span>{rows.length} invoice records</span></div>
<div class="card table-wrap"><table class="data-table"><thead><tr><th>Invoice</th><th>Type</th><th>Customer</th><th>Project</th><th>Total</th><th>Received</th><th>Created</th><th></th></tr></thead><tbody>{#each rows as row}<tr><td><a class="invoice-link" href={'/invoices/'+row.invoice.id}><strong>{row.invoice.number}</strong><small>{row.invoice.id}</small></a></td><td>{row.invoice.kind === 'advance' ? 'Advance receipt' : row.invoice.kind === 'payment' ? 'Payment receipt' : row.invoice.kind === 'partial' ? 'Partial work invoice' : 'Final invoice'}</td><td>{row.order?.customer || 'Order unavailable'}</td><td>{row.order?.project || row.invoice.orderId}</td><td>{row.invoice.total ? money(row.invoice.total) : row.order?.priceSet===false?'Not set':money(Math.max(0,(row.order?.price||0)-(row.order?.discount||0)))}</td><td>{row.invoice.amountReceived ? money(row.invoice.amountReceived) : money(row.invoice.paid || row.order?.paid || 0)}</td><td>{formatDateTime(row.invoice.openedAt)}</td><td><a class="arrow-button" href={'/invoices/'+row.invoice.id} aria-label="Open invoice"><ArrowUpRight size={15}/></a></td></tr>{/each}</tbody></table>{#if !rows.length}<p class="empty">No invoice records yet. Generate one from an order or payment.</p>{/if}</div>

<style>.invoice-summary{display:flex;gap:16px;align-items:center;margin-bottom:18px}.invoice-summary>div{min-width:180px;border:1px solid var(--line);border-radius:14px;background:var(--card);padding:14px 17px;display:flex;flex-direction:column;gap:5px}.invoice-summary span,.invoice-tools span{font-size:9px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}.invoice-summary strong{font-size:19px}.invoice-summary>a{margin-left:auto;display:flex;align-items:center;gap:7px}.invoice-tools{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.filter{width:260px;display:flex;align-items:center;gap:8px;border:1px solid var(--line);background:var(--card);border-radius:10px;padding:0 11px;color:var(--muted)}.filter input{height:36px;flex:1;border:0;background:transparent;color:inherit;outline:0}.invoice-link{display:flex;flex-direction:column;gap:3px;color:inherit}.invoice-link:hover strong{color:var(--purple)}.arrow-button{width:30px;height:30px;border:1px solid var(--line);border-radius:8px;display:grid;place-items:center;color:var(--purple);transition:.18s}.arrow-button:hover{transform:translate(2px,-2px);border-color:var(--purple);background:var(--theme-soft)}.empty{text-align:center;color:var(--muted);font-size:10px;padding:34px}@media(max-width:650px){.invoice-summary>div:nth-child(2){display:none}.invoice-summary>div{min-width:0}.invoice-tools span{display:none}}</style>
