	<script lang="ts">
		import { enhance } from '$app/forms';
		import type { SubmitFunction } from '@sveltejs/kit';
		import { CheckCircle2, Database, KeyRound, LogOut, Plus, RefreshCw, ShieldCheck, Sheet, TriangleAlert } from '@lucide/svelte';
		let { data, form } = $props();
		let creating = $state(false);
		let pendingAction = $state('');
		const track = (key: string): SubmitFunction => () => {
			pendingAction = key;
			return async ({ update }) => {
				try { await update(); }
				finally { pendingAction = ''; }
			};
		};
	</script>

<svelte:head><title>Client control — StudioFlow</title><meta name="robots" content="noindex,nofollow" /></svelte:head>
<header class="owner-head"><a href="/owner"><b>SF</b><span><strong>StudioFlow</strong><small>Owner control</small></span></a><div><span>{data.account?.email || 'Owner'}</span><a href="/logout"><LogOut size={15}/>Sign out</a></div></header>
<main class="owner-main">
	<section class="intro"><div><p>Master workspace control</p><h1>Client accounts and stored services</h1><span>Create clients, review their saved Neon and Sheet setup, and manage login access from one place.</span></div><button onclick={() => creating = !creating}><Plus size={16}/>{creating ? 'Close setup' : 'Add new client'}</button></section>
	{#if form?.error}<div class="owner-notice error"><TriangleAlert size={16}/>{form.error}</div>{:else if form?.success}<div class="owner-notice success"><CheckCircle2 size={16}/>{form.success}</div>{/if}

	{#if creating}
	<section class="panel create-panel"><h2>Create a client workspace</h2><p>First create the Neon database and Google Sheet, then enter the saved services and the client's first login ID below.</p>
		<form method="POST" action="?/create" use:enhance={track('create')}>
			<div class="grid"><label>Internal client name<small>Only visible in master control.</small><input name="internalName" placeholder="Example: Anjana Creations" required /></label><label>Workspace URL name<small>Lowercase letters, numbers, and hyphens.</small><input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="anjana-creations" required /></label><label>Studio display name<small>Shown inside the client's workspace.</small><input name="studioName" required /></label><label>Logo URL <small>Optional HTTPS image address.</small><input name="logoUrl" placeholder="https://…" /></label><label>Client login ID (email)<small>The client uses this on the main sign-in page.</small><input name="email" type="email" autocomplete="off" required /></label><label>First password<small>Minimum 10 characters; the owner can reset it later.</small><input name="password" type="password" minlength="10" autocomplete="new-password" required /></label><label class="wide">Neon database connection URL<small>Stored encrypted and never displayed again.</small><input name="databaseUrl" type="password" autocomplete="off" required /></label><label>Google Sheet ID<small>Saved so this workspace syncs to the correct Sheet.</small><input name="googleSheetId" required /></label><label>Orders sheet tab<small>Usually keep this as Orders.</small><input name="ordersTab" value="Orders" required /></label></div>
			<div class="checks"><label><input name="attachExisting" type="checkbox" /> I reviewed and want to attach existing StudioFlow data</label><label><input name="isDemo" type="checkbox" /> This is a resettable demo tenant</label></div>
			<button class="primary" disabled={pendingAction !== ''} aria-busy={pendingAction === 'create'}>{#if pendingAction === 'create'}<RefreshCw class="loading-icon" size={15}/>{:else}<Plus size={15}/>{/if}{pendingAction === 'create' ? 'Validating…' : 'Validate and create client'}</button>
		</form>
	</section>
	{/if}

	<section class="tenant-grid">
		{#each data.tenants as tenant}
		<article class="panel tenant-card">
			<div class="tenant-top"><div class="tenant-logo">{#if tenant.logoUrl}<img src={tenant.logoUrl} alt="" />{:else}{tenant.internalName.slice(0,2).toUpperCase()}{/if}</div><div><span class="slug">Workspace /{tenant.slug}</span><h2>{tenant.internalName}</h2><p>{tenant.studioName}</p></div><span class:healthy={tenant.connectionStatus === 'healthy'} class:error-state={tenant.connectionStatus === 'error'} class="health">{tenant.connectionStatus}</span></div>
			<div class="facts"><span><Database size={15}/><small>Neon database</small><b>Stored securely</b><em>Encrypted connection URL</em></span><span><Sheet size={15}/><small>Google Sheet</small><b>{tenant.googleSheetId ? `${tenant.googleSheetId.slice(0,8)}…${tenant.googleSheetId.slice(-4)}` : 'Not configured'}</b><em>Tab: {tenant.ordersTab || 'Orders'}</em></span><span><KeyRound size={15}/><small>Client login ID</small><b>{tenant.adminEmail}</b><em>{tenant.activeSessions} active session{tenant.activeSessions === 1 ? '' : 's'}</em></span></div>
			{#if tenant.connectionError}<div class="connection-error">{tenant.connectionError}</div>{/if}
			<div class="actions">
				<form method="POST" action="?/test" use:enhance={track(`test:${tenant.id}`)}><input type="hidden" name="tenantId" value={tenant.id}/><button disabled={pendingAction !== ''} aria-busy={pendingAction === `test:${tenant.id}`}>{#if pendingAction === `test:${tenant.id}`}<RefreshCw class="loading-icon" size={13}/>{:else}<RefreshCw size={13}/>{/if}{pendingAction === `test:${tenant.id}` ? 'Testing…' : 'Test connections'}</button></form>
				<form method="POST" action="?/status" use:enhance={track(`status:${tenant.id}`)}><input type="hidden" name="tenantId" value={tenant.id}/><select name="status" value={tenant.status} disabled={pendingAction !== ''}><option value="draft">Draft</option><option value="active">Active</option><option value="suspended">Suspended</option></select><button disabled={pendingAction !== ''} aria-busy={pendingAction === `status:${tenant.id}`}>{#if pendingAction === `status:${tenant.id}`}<RefreshCw class="loading-icon" size={13}/>{/if}{pendingAction === `status:${tenant.id}` ? 'Saving…' : 'Save status'}</button></form>
			</div>
			<details><summary>Change client login ID or reset password</summary><div class="detail-copy">The current login ID is shown below. Leave the password empty to keep it unchanged. Saving signs out the client's existing sessions.</div><form method="POST" action="?/credentials" class="credential-form" use:enhance={track(`credentials:${tenant.id}`)}><input type="hidden" name="tenantId" value={tenant.id}/><label>Client login ID<input name="email" type="email" value={tenant.adminEmail} autocomplete="off" required/></label><label>New password <small>Optional · minimum 10 characters</small><input name="password" type="password" minlength="10" autocomplete="new-password" placeholder="Leave empty to keep current password"/></label><button disabled={pendingAction !== ''} aria-busy={pendingAction === `credentials:${tenant.id}`}>{#if pendingAction === `credentials:${tenant.id}`}<RefreshCw class="loading-icon" size={13}/>{/if}{pendingAction === `credentials:${tenant.id}` ? 'Saving login…' : 'Save login and sign out sessions'}</button></form></details>
			<details><summary>Review or replace stored services</summary><div class="stored-status"><span><Database size={13}/><b>Neon URL</b><small>Encrypted and stored</small></span><span><Sheet size={13}/><b>Sheet ID</b><small>{tenant.googleSheetId || 'Not configured'}</small></span></div><form method="POST" action="?/connections" class="connection-form" use:enhance={track(`connections:${tenant.id}`)}><input type="hidden" name="tenantId" value={tenant.id}/><label>Studio display name<input name="studioName" value={tenant.studioName} required/></label><label>Logo URL<input name="logoUrl" value={tenant.logoUrl} placeholder="Optional HTTPS logo URL"/></label><label class="wide">Replace Neon URL <small>Leave empty to keep the encrypted URL already stored.</small><input name="databaseUrl" type="password" autocomplete="off" placeholder="Paste only when replacing the database connection"/></label><label>Google Sheet ID<input name="googleSheetId" value={tenant.googleSheetId}/></label><label>Orders sheet tab<input name="ordersTab" value={tenant.ordersTab} placeholder="Orders"/></label><button disabled={pendingAction !== ''} aria-busy={pendingAction === `connections:${tenant.id}`}>{#if pendingAction === `connections:${tenant.id}`}<RefreshCw class="loading-icon" size={13}/>{/if}{pendingAction === `connections:${tenant.id}` ? 'Checking services…' : 'Validate and save services'}</button></form></details>
			{#if tenant.isDemo}<details class="danger"><summary>Reset demo data</summary><form method="POST" action="?/reset" class="inline-form" use:enhance={track(`reset:${tenant.id}`)}><input type="hidden" name="tenantId" value={tenant.id}/><input name="confirmation" placeholder="Type RESET" required/><button disabled={pendingAction !== ''} aria-busy={pendingAction === `reset:${tenant.id}`}>{#if pendingAction === `reset:${tenant.id}`}<RefreshCw class="loading-icon" size={13}/>{/if}{pendingAction === `reset:${tenant.id}` ? 'Resetting…' : 'Reset database and Sheet'}</button></form></details>{/if}
		</article>
		{/each}
		{#if !data.tenants.length}<div class="panel empty">No clients yet. Add the first isolated workspace.</div>{/if}
	</section>
	<section class="panel owner-security"><ShieldCheck size={20}/><div><h2>Master owner password</h2><p>Use at least 10 characters. Saving immediately signs out every master-owner session, including this one.</p></div><form method="POST" action="?/ownerPassword" use:enhance={track('owner-password')}><label>New master password<input name="password" type="password" minlength="10" autocomplete="new-password" placeholder="Enter a new master password" required/></label><button disabled={pendingAction !== ''} aria-busy={pendingAction === 'owner-password'}>{#if pendingAction === 'owner-password'}<RefreshCw class="loading-icon" size={13}/>{/if}{pendingAction === 'owner-password' ? 'Changing password…' : 'Change master password'}</button></form></section>
</main>

<style>
	.owner-head{height:68px;padding:0 max(22px,calc((100vw - 1180px)/2));display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);background:var(--card)}.owner-head>a,.owner-head>div,.owner-head>div>a{display:flex;align-items:center;gap:10px}.owner-head>a>b{width:35px;height:35px;border-radius:10px;background:var(--purple);color:white;display:grid;place-items:center}.owner-head a span{display:flex;flex-direction:column}.owner-head strong{font-size:12px}.owner-head small,.owner-head>div>span{font-size:8px;color:var(--muted)}.owner-head>div>a{font-size:9px;color:var(--purple)}
	.owner-main{max-width:1180px;margin:0 auto;padding:36px 22px 80px}.intro{display:flex;justify-content:space-between;align-items:end;margin-bottom:22px}.intro p,.slug{margin:0 0 6px;color:var(--purple);font-size:9px;text-transform:uppercase;letter-spacing:.1em}.intro h1{font-size:26px;margin:0 0 7px}.intro span{font-size:10px;color:var(--muted)}.intro button,.primary{display:flex;align-items:center;gap:7px;border:0;border-radius:9px;background:var(--purple);color:white;padding:11px 15px}.owner-notice{position:static;display:flex;align-items:flex-start;gap:8px;width:100%;box-sizing:border-box;padding:12px 14px;border-radius:10px;margin:0 0 16px;font-size:10px;line-height:1.45}.owner-notice :global(svg){flex:0 0 auto;margin-top:1px}.owner-notice.error,.connection-error{background:#ef444412;color:#ef4444}.owner-notice.success{background:#10b98112;color:#059669}
	.panel{border:1px solid var(--line);border-radius:15px;background:var(--card);padding:20px}.create-panel{margin-bottom:20px}.panel h2{margin:0;font-size:14px}.panel>p{font-size:9px;color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin:18px 0}.grid label,.credential-form label,.connection-form label,.owner-security label{display:grid;gap:6px;font-size:9px;color:var(--theme-text);font-weight:650}.grid label small,.credential-form label small,.connection-form label small{color:var(--muted);font-size:7px;font-weight:450;line-height:1.35}.grid .wide,.connection-form .wide{grid-column:1/-1}.checks{display:flex;gap:20px;margin-bottom:16px}.checks label{display:flex;align-items:center;gap:6px;font-size:9px;color:var(--muted)}.checks input{width:auto}
	.tenant-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.tenant-top{display:flex;align-items:center;gap:12px}.tenant-logo{width:43px;height:43px;overflow:hidden;border-radius:11px;background:var(--theme-soft);color:var(--purple);display:grid;place-items:center;font-size:10px;font-weight:700}.tenant-logo img{width:100%;height:100%;object-fit:contain}.tenant-top h2{margin:0 0 3px}.tenant-top p{margin:0;color:var(--muted);font-size:9px}.tenant-top .health{margin-left:auto;border-radius:20px;background:var(--theme-soft);padding:5px 8px;font-size:8px;text-transform:capitalize}.health.healthy{color:#059669}.health.error-state{color:#ef4444}
	.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:17px 0}.facts>span{min-width:0;padding:11px;border:1px solid var(--line);border-radius:10px;display:grid;gap:4px;color:var(--purple);background:color-mix(in srgb,var(--theme-soft) 34%,var(--card))}.facts b{font-size:8px;color:var(--theme-text);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.facts small{font-size:7px;color:var(--muted);font-weight:650}.facts em{font-size:7px;color:var(--muted);font-style:normal;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.connection-error{padding:8px;border-radius:8px;font-size:8px;overflow-wrap:anywhere}
	.actions{display:flex;gap:8px;margin-top:13px}.actions form{display:flex;gap:5px;flex:1}.actions button,.actions select,details button,.owner-security button{height:36px;border:1px solid var(--line);border-radius:8px;background:var(--card);color:var(--purple);font-size:8px;padding:0 10px}.actions button,details button,.owner-security button{display:flex;align-items:center;justify-content:center;gap:5px}.actions select{min-width:90px}button:disabled,select:disabled{cursor:wait;opacity:.58}:global(.loading-icon){animation:owner-spin .75s linear infinite}@keyframes owner-spin{to{transform:rotate(360deg)}}
	details{border-top:1px solid var(--line);margin-top:13px;padding-top:12px}summary{cursor:pointer;color:var(--theme-text);font-size:9px;font-weight:650}.detail-copy{margin:9px 0 11px;color:var(--muted);font-size:8px;line-height:1.5}.credential-form,.connection-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}.credential-form button,.connection-form button{align-self:end;min-height:40px;height:auto;line-height:1.3}.credential-form button{grid-column:1/-1}.connection-form button{grid-column:1/-1}.stored-status{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:10px}.stored-status span{display:grid;grid-template-columns:auto 1fr;align-items:center;column-gap:6px;padding:9px;border-radius:8px;background:var(--theme-soft);color:var(--purple)}.stored-status b{font-size:8px;color:var(--theme-text)}.stored-status small{grid-column:2;font-size:7px;color:var(--muted);overflow:hidden;text-overflow:ellipsis}.inline-form{display:grid;grid-template-columns:1fr 1fr auto;gap:7px;margin-top:10px}.danger summary,.danger button{color:#ef4444}
	.owner-security{display:flex;align-items:center;gap:13px;margin-top:20px;color:var(--purple)}.owner-security>div{flex:1}.owner-security p{max-width:540px;margin:5px 0 0;color:var(--muted);font-size:8px;line-height:1.45}.owner-security form{display:flex;align-items:end;gap:8px}.owner-security label{min-width:230px}.empty{text-align:center;color:var(--muted);grid-column:1/-1}
	@media(max-width:850px){.tenant-grid{grid-template-columns:1fr}.grid{grid-template-columns:1fr}.grid .wide{grid-column:auto}.intro{align-items:flex-start;gap:18px}.owner-security{align-items:flex-start;flex-direction:column}.owner-security form{width:100%}.owner-security label{flex:1}.inline-form{grid-template-columns:1fr}.owner-head>div>span{display:none}}
	@media(max-width:560px){.intro{flex-direction:column}.facts,.stored-status,.credential-form,.connection-form{grid-template-columns:1fr}.connection-form .wide,.credential-form button,.connection-form button{grid-column:auto}.checks,.actions{flex-direction:column}.owner-security form{width:100%;align-items:stretch;flex-direction:column}.owner-security label{min-width:0}}
</style>
