<script lang="ts">
	import Modal from './Modal.svelte';
	import EditorModal from './EditorModal.svelte';
	import type { Editor, Task } from '$lib/types';
	let { open = $bindable(), orderId, editors = $bindable(), task = null, onsaved = () => {} }: { open:boolean; orderId:string; editors:Editor[]; task?:Task|null; onsaved?:()=>void }=$props();
	let titles=$state(''); let editorId=$state(''); let due=$state(''); let instructions=$state(''); let textLink=$state(''); let imageUrl=$state(''); let billableAmount=$state<number|undefined>(undefined); let error=$state(''); let saving=$state(false); let showEditor=$state(false);
	$effect(()=>{if(open){titles=task?.name||'';editorId=task?.editorId||'';due=task?.due||'';instructions=task?.instructions||'';textLink=task?.textLink||'';imageUrl=task?.imageUrl||'';billableAmount=task?.billableAmount||undefined;error=''}});
	function parseLine(line:string){const divider=line.lastIndexOf('|');if(divider<0)return{name:line,billableAmount:0};const amount=Number(line.slice(divider+1).trim().replaceAll(',',''));return Number.isFinite(amount)?{name:line.slice(0,divider).trim(),billableAmount:Math.max(0,amount)}:{name:line,billableAmount:0}}
	async function save(){const names=titles.split('\n').map((value)=>value.trim()).filter(Boolean);if(!names.length){error='Add at least one task title.';return}if(!editorId){error='Choose or create an editor.';return}saving=true;const endpoint=task?`/api/tasks/${task.id}`:`/api/orders/${orderId}/tasks`;const body=task?{name:names[0],editorId,due,instructions,textLink,imageUrl,billableAmount:billableAmount??0}:{tasks:names.map((line)=>({...parseLine(line),editorId,due,instructions,textLink,imageUrl}))};const response=await fetch(endpoint,{method:task?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json();saving=false;if(!response.ok){error=result.error||'Unable to save task';return}open=false;onsaved()}
	function editorSaved(editor:Editor){editors=[...editors,editor];editorId=editor.id}
</script>
<Modal title={task?'Edit task':'Assign work'} bind:open wide>
	<div class="field"><label for="task-titles">{task?'Task title':'Task titles — one per line (optional price after |)'}</label><textarea id="task-titles" bind:value={titles} placeholder={task?'Culling':'Culling | 3000&#10;Colour correction | 5000&#10;Quality check'}></textarea></div>
	<div class="form-grid task-fields"><div class="field"><label for="task-editor">Editor *</label><div class="editor-select"><select id="task-editor" bind:value={editorId}><option value="">Choose editor</option>{#each editors.filter((editor)=>editor.availability!=='inactive') as editor}<option value={editor.id}>{editor.name} · {editor.activeTasks} active</option>{/each}</select><button class="secondary" onclick={()=>showEditor=true}>New</button></div></div><div class="field"><label for="task-due">Due date</label><input id="task-due" type="date" bind:value={due}/></div></div>
	{#if task}<div class="field section"><label for="task-value">Billable task value (₹)</label><input id="task-value" type="number" min={task.invoicedAmount||0} step="1" bind:value={billableAmount} placeholder="Set before partial invoicing"/>{#if (task.invoicedAmount||0)>0}<small class="invoiced-note">Already invoiced: ₹{(task.invoicedAmount||0).toLocaleString('en-IN')}</small>{/if}</div>{:else}<p class="value-note">Example: <b>Colour correction | 5000</b>. The value is used when partially invoicing completed work.</p>{/if}
	<div class="field section"><label for="task-instructions">Instructions</label><textarea id="task-instructions" bind:value={instructions}></textarea></div>
	<div class="form-grid section"><div class="field"><label for="task-link">External text / reference link</label><input id="task-link" type="url" inputmode="url" bind:value={textLink} placeholder="https://..."/></div><div class="field"><label for="task-image">External image URL</label><input id="task-image" type="url" inputmode="url" bind:value={imageUrl} placeholder="https://..."/></div></div>
	<p class="media-note">Files stay in Drive, R2, S3 or your chosen file host. StudioFlow stores only the external link.</p>
	{#if error}<p class="error">{error}</p>{/if}
	{#snippet footer()}<button class="secondary" onclick={()=>open=false}>Cancel</button><button class="primary" disabled={saving} onclick={save}>{saving?'Saving...':task?'Update task':'Assign tasks'}</button>{/snippet}
</Modal>
<EditorModal bind:open={showEditor} onsaved={editorSaved}/>
<style>.task-fields,.section{margin-top:18px}.editor-select{display:grid;grid-template-columns:1fr auto;gap:7px}.media-note,.value-note,.invoiced-note{margin:8px 0 0;color:var(--muted);font-size:8px}.value-note b{color:var(--text)}.invoiced-note{display:block}.error{color:#ef4444;font-size:10px;margin-top:12px}</style>
